

POST http://localhost:8081/signup
content-type: application/json

{
    "user_name":"kiyo",
    "email_address":"te@st.com",
    "password":"aaaaaa"
}

###

GET http://localhost:8081/login?emailAddress=te@st.com&password=admin1234


###

GET http://localhost:8081/healthz


