name: Build and Push Image to Google Cloud Platfrom
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: aninaka-user-auth-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCR_PROJECT_ID }}
          export_default_credentials: true
      - name: create GIT_TAG
        run: echo "GIT_TAG="production-$(git rev-parse --short HEAD)"" >> $GITHUB_ENV
      - name: Build Docker Image
        run: docker build -t ${{ secrets.GCR_REGION }}/${{ secrets.GCR_PROJECT_ID }}/$IMAGE_NAME:${{ env.GIT_TAG }} .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          docker push ${{ secrets.GCR_REGION }}/${{ secrets.GCR_PROJECT_ID }}/$IMAGE_NAME:${{ env.GIT_TAG }}
